export default [
	{
		movieID: 62,
		title: "2001: A Space Odyssey",
		poster: "/zmmYdPa8Lxx999Af9vnVP4XQ1V6.jpg",
		backdrop: "/spoZUN4X1KiOc5S0plOyGAXLNtb.jpg",
		id: "2001-A-Space-Odyssey",
	},
	{
		movieID: 710,
		title: "GoldenEye",
		poster: "/z0ljRnNxIO7CRBhLEO0DvLgAFPR.jpg",
		backdrop: "/vm7yMg7YiYisMSeO3mUC5NUKbSB.jpg",
		id: "GoldenEye",
	},
	{
		movieID: 25623,
		title: "HOUSE",
		poster: "/a5MOHiQhuHTR4xn2GPo8awOj4dM.jpg",
		backdrop: "/gwH3ai9WPrD2RfIF6TaaR5ATWwp.jpg",
		id: "house1977",
	},
	{
		movieID: 313369,
		title: "La La Land",
		poster: "/q0dsNZOuSKzAdZod9ohPXJ4GQUs.jpg",
		backdrop: "/qJeU7KM4nT2C1WpOrwPcSDGFUWE.jpg",
		id: "la-la-land",
	},
	{
		movieID: 530385,
		title: "Midsommar",
		poster: "/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg",
		backdrop: "/g6GtOfXtzDpY73ef7wludoorTti.jpg",
		id: "midsommar",
	},
	{
		movieID: 83666,
		title: "Moonrise Kingdom",
		poster: "/wOgmhrSUwOuZJsQXf2GsI923N0f.jpg",
		backdrop: "/bsYv9IFIGfpAV0oUbe7YTiyxhox.jpg",
		id: "moonrise-kingdom",
	},
	{
		movieID: 26679,
		title: "Blade Runner 2049",
		poster: "/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
		backdrop: "/sAtoMqDVhNDQBc3QJL3RF6hlhGq.jpg",
		id: "blade-runner-2049",
	},
	{
		movieID: 26679,
		title: "Spookies",
		poster: "/mmJN1NvMIVQaWvO3iWvdSppfFy3.jpg",
		backdrop: "/9QVYbdRUPJFFlK2b3rnzjU9JM2D.jpg",
		id: "spookies",
	},
	{
		movieID: 548473,
		title: "Color Out of Space",
		poster: "/vkwgzCBBiY3C1XEy0WakYfMOvnG.jpg",
		backdrop: "/iyn2JQsftaqhQlXYaCCvn8udM5i.jpg",
		id: "color-out-of-space",
	},
];
